application: www-spearce-org
version: 1
runtime: python
api_version: 1
default_expiration: 7d

handlers:
- url: /application_version
  static_files: static/application_version
  mime_type: text/plain
  expiration: 1s
  upload: static/application_version

- url: /robots.txt
  static_files: static/robots.txt
  mime_type: text/plain
  upload: static/robots.txt

- url: .*
  script: redirect.py
